[".config/antidote"]
    type = "git-repo"
    url = "https://github.com/mattmc3/antidote.git"
    refreshPeriod = "168h"
    [".config/antidote".clone]
        args = ["--depth=1"]
{{- if eq .chezmoi.hostname "pepchain" }}
[".config/aux"]
    type = "git-repo"
    url = "https://github.com/eljobe/aux-pepchain.git"
    refreshPeriod = "168h"
{{- end}}
