name: Sync Dotfiles to Servers

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */1 * * *'  # Retry every hour

jobs:
  sync-dotfiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ssh utility
        uses: actions/checkout@v4
        with:
          repository: eljobe/tailscale-multi-ssh

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.1'

      - name: Build Go binary
        run: go build -o multi-ssh

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ghaction
          version: 1.72.1

      - name: Run Sync Updates
        run: ./multi-ssh -sshuser=${{ secrets.TS_USER }} -sshcommand="chezmoi update" -tag="tag:chezmoi"
