name: Sync Dotfiles to Servers

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */4 * * *'  # Retry every 4 hours

jobs:
  sync-dotfiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ghaction
          version: 1.72.1

      - name: Show tailscale status
        run: |
          tailscale status

      # - name: Sync to Sever 1
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ${{ secrets.TS_USER }}@${{ secrets.TS_HOST_1 }} "chezmoi update"

      - name: Sync to Server 1
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TS_HOST_1 }}
          username: ${{ secrets.TS_USER }}
          script: chezmoi update

      - name: Sync to Server 2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TS_HOST_2 }}
          username: ${{ secrets.TS_USER }}
          script: chezmoi update

      - name: Sync to Server 3
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TS_HOST_3 }}
          username: ${{ secrets.TS_USER }}
          script: chezmoi update

      - name: Sync to Server 4
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TS_HOST_4 }}
          username: ${{ secrets.TS_USER }}
          script: chezmoi update
